### PR TITLE
Sticky social media sidebar

### LINKED ISSUE #285: Sticky social media sidebar
I want to add a sticky social media sidebar in the home page.
Please assign me this issue. Thanks

### PR DESCRIPTION
**Pull request by gayatri517**
Closes #285 

### Screenshot

image

Kindly review it.
Thank you.

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Can you do it on the right side and also please hide in for mobile view

**Comment by gayatri517** [comment]
@AdityaTeltia I have made the changes, Kindly review them
Thank you

**Comment by gayatri517** [comment]
@ArunTeltia Can you please let me know if this PR is going to be merged under GSSOC because a lot of changes have been done in this PR since then.

**Comment by gayatri517** [comment]
@ArunTeltia Kindly review my PR.

**Comment by ArunTeltia** [comment]
can you have a look at the conflicts @gayatri517 and sorry I totally forgot about this issue

**Comment by ArunTeltia** [comment]
Take help of @LordShenron if you dont know how to resolve conflicts

**Comment by gayatri517** [comment]
@ArunTeltia @LordShenron all the conflicting issues have been resolved.
Kindly review it

**Comment by ArunTeltia** [comment]
LGTM merging, 
Thank you for contributing to Project Sakura @gayatri517

**Pull request merged**
