### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by DevrajDC**
-> updated readme
-> added Style guide
-> updated Team section on readme.

### CODE REVIEW

**Comment by LordShenron** [comment]
Didn't I already merged this?

**Comment by ArunTeltia** [comment]
Can You create this in a branch by rebasing, it have conflict and also your carousal PR is submerged in this

**Comment by ArunTeltia** [comment]
> Didn't I already merged this?

Actually he is trying to add color pallete to the readme

**Comment by LordShenron** [comment]
> > Didn't I already merged this?
> 
> Actually he is trying to add color pallete to the readme

Closing this one then.

**Pull request closed without merging**
