### PR TITLE
mantainer(a9ito) added

### PR DESCRIPTION
**Pull request by ArunTeltia**
joyeuse capitalised in dowload

### CODE REVIEW

**Review by LordShenron — APPROVED** [review]
In stats too right?

**Comment by LordShenron** [comment]
Also can u mark it as Global variant

**Comment by ArunTeltia** [comment]
yeah 
stats is refractored in the previous pr
stats and download depend on mantainer.js now 💯

**Comment by LordShenron** [comment]
@ArunTeltia i meant all capital for joyeuse in stats page too

**Comment by ArunTeltia** [comment]
Global varient marked

**Pull request merged**
