### PR TITLE
Added hover effects in footer of homepage

### PR DESCRIPTION
**Pull request by FireQueen-3010**
Part 1 of #198

Hover feature in footer of home page

### Screenshot

https://user-images.githubusercontent.com/59244300/112938205-d4459400-9146-11eb-8267-7c47449048ee.mp4

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ArunTeltia @LordShenron

**Review by LordShenron — APPROVED** [review]
Looks fine to me

**Review by ArunTeltia — APPROVED** [review]

**Comment by ArunTeltia** [comment]
Merge @LordShenron

**Comment by FireQueen-3010** [comment]
Yeah pls do @LordShenron :)

**Pull request merged**
