### PR TITLE
Delete Unwanted internal Css and minimize the Css files.

### PR DESCRIPTION
**Pull request by Shivam-Shandilya1**
I have deleted the unwanted internal css and minimizes the number of CSS files without afffecting the website.

### CODE REVIEW

**Comment by ArunTeltia** [comment]
These files that you have deleted are not unused there are many css files that i can point in these that are bieng used in the project and merging this pr will completely break the website. Can You tell me the point of this PR

**Comment by ArunTeltia** [comment]
@cryptofox17 can you help him, I think he is lost and since you also helped in deleting the unwanted css You can tell him the problem with this PR

**Comment by cryptofox17** [comment]
@Shivam-Shandilya1 did you running the website after removing those codes? 
You have removed bootstrap-responsive.css. Although 90% of the classes in it are unused, there are few which are in use (eg clearfix, navbar). So please look into this.

**Comment by Shivam-Shandilya1** [comment]
Okay ! I understand the mistake ,I will retry .Thanks @cryptofox17 and @ArunTeltia

**Comment by cryptofox17** [comment]
@Shivam-Shandilya1 try using coverage in chrome tools, it'll make it easier but you still need to check if it's running fine after removing Classes

**Pull request closed without merging**
