### PR TITLE
Website: Device Maintainers: Drop Beryllium and Ginkgo/Willow

### PR DESCRIPTION
**Pull request by xmxrtyx**

### CODE REVIEW

**Comment by CyberJalagam** [comment]
@xmxrtyx ;-;

**Comment by xmxrtyx** [comment]
> @xmxrtyx ;-;

🗿🗿🗿🗿🗿🗿🗿

**Review by LordShenron — APPROVED** [review]

**Comment by CyberJalagam** [comment]
@xmxrtyx Sed

**Comment by xmxrtyx** [comment]
> @xmxrtyx Sed

indeed (╥﹏╥)

**Pull request merged**
