### PR TITLE
added hover effect on brand

### PR DESCRIPTION
**Pull request by satcasm**
Issue Reference: #239

### CODE REVIEW

**Comment by LordShenron** [comment]
A preview will make reviewing this much easier.

**Comment by satcasm** [comment]
Hey @LordShenron apologies for late response.
Preview:


https://user-images.githubusercontent.com/56315878/114845278-454ca300-9df9-11eb-82fd-587fdfc14e5c.mp4

**Comment by satcasm** [comment]
Hey @LordShenron apologies for bringing this late...but the level tag is inaccurate so it's points are not showing on leader board...It should be `Level0`.
Thanks!

**Comment by LordShenron** [comment]
> Hey @LordShenron apologies for bringing this late...but the level tag is inaccurate so it's points are not showing on leader board...It should be `Level1`.
> Thanks!

It's not case sensitive afaik.. coz we cannot have Level1 and level1 tags at the same time

**Comment by satcasm** [comment]
@LordShenron , yeah you are right... idk how it's showing now, sorry for bothering you.

**Pull request merged**
