### PR TITLE
Stats UI

### PR DESCRIPTION
**Pull request by tanishq-arya**
1. Added a new bootstrap theme to stats page (bootstrap-ui.css)
2. Modified stat.html file
3. Modified Footer

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Can you share some images @tanishq-arya

**Comment by tanishq-arya** [comment]
Screenshot (954)
Screenshot (951)
Screenshot (952)
Screenshot (953)

**Comment by tanishq-arya** [comment]
Also I would like to suggest that you can define a color palette for the whole website and all UI can be made according to that. Some issues of ui/ux are working on that I guess

**Comment by ArunTeltia** [comment]
Sorry for the delay, LGTM @LordShenron  Merge this

**Comment by DevrajDC** [comment]
> Also I would like to suggest that you can define a color palette for the whole website and all UI can be made according to that. Some issues of ui/ux are working on that I guess

We already have made a color palette. Will update you about it soon and than you can make the necessary color changes in stats page.

**Review by LordShenron — APPROVED** [review]
Looks good to me, Should we merge it for now?

**Comment by ArunTeltia** [comment]
Yes We should for now

**Comment by LordShenron** [comment]
@tanishq-arya resolve the conflicts :P

**Comment by tanishq-arya** [comment]
it is showing conflicts in files which I didn't even change.

**Comment by tanishq-arya** [comment]
> it is showing conflicts in files which I didn't even change.

Thanks @LordShenron

**Comment by LordShenron** [comment]
> > it is showing conflicts in files which I didn't even change.
> 
> Thanks @LordShenron. Should I delete this branch now ?

Upto you

**Comment by tanishq-arya** [comment]
@ArunTeltia Can you please add gssoc label to this PR

**Comment by ArunTeltia** [comment]
Sorry for the delay here you go @tanishq-arya

**Comment by tanishq-arya** [comment]
No issues. Thanks.

**Pull request merged**
