### PR TITLE
Reference to issue #251

### PR DESCRIPTION
**Pull request by RahulBansal0502**
Before:
image

Now:
image

### CODE REVIEW

**Review by ArunTeltia — APPROVED** [review]
@LordShenron  merge this 

@RahulBansal0502 just an advice please write good title for the PR(that state more about the problem you resolve) thats usually a good practice otherwise solid work

Just curios if this works for all the views (Mobile and 1100 to 1300 px PC)

**Comment by LordShenron** [comment]
> @LordShenron merge this
> 
> @RahulBansal0502 just an advice please write good title for the PR(that state more about the problem you resolve) thats usually a good practice otherwise solid work
> 
> Just curios if this works for all the views (Mobile and 1100 to 1300 px PC)

On mobile devices everything is in straight line.

**Comment by ArunTeltia** [comment]
I am not sure but In my PC it is still having issues

**Comment by LordShenron** [comment]
> I am not sure but In my PC it is still having issues

It's still having issues. Confirmed.

**Pull request merged**
