### PR TITLE
github workflow added

### PR DESCRIPTION
**Pull request by ArunTeltia**

### CODE REVIEW

**Review by LordShenron — COMMENTED** [review]
My god why!

**Comment by ArunTeltia** [comment]
for adding self tags.

**Comment by LordShenron** [comment]
how high are the chances that will tag every pr as a gssoc'21?

**Comment by ArunTeltia** [comment]
I kanged it from one of the organisation workflow XD

**Comment by LordShenron** [comment]
> I kanged it from one of the organisation workflow XD

Krke dekhe kya merge? xD force push krdunga issue hua to

**Comment by ArunTeltia** [comment]
check this https://github.com/internetarchive/openlibrary/issues/new/choose

**Comment by ArunTeltia** [comment]
Karde mast lag raha mujhe lets try

**Review by LordShenron — APPROVED** [review]
Go go go go

**Comment by ArunTeltia** [comment]
Fucking Sick bruh @LordShenron

**Comment by LordShenron** [comment]
> Fucking Sick bruh @LordShenron

sick what?

**Comment by ArunTeltia** [comment]
Issue creation karke dekh abhi ek issue hai squash kariyo ek or pr maar raha mei

**Comment by LordShenron** [comment]
> Issue creation karke dekh abhi ek issue hai squash kariyo ek or pr maar raha mei

yup kar kar i am free rn

**Pull request merged**
