### PR TITLE
contributors section updated

### PR DESCRIPTION
**Pull request by vedikaag99**
@ArunTeltia done. Please review.

### CODE REVIEW

**Review by yasharth291 — APPROVED** [review]

**Comment by LordShenron** [comment]
@ArunTeltia the maintainers and contributors list should be moved to a new page ig. There is too much content to display on landing page now.

**Comment by ArunTeltia** [comment]
I am thinking of creating a seperate page for it, Send me the Card based theme that you want, i will create a js file for all the mantainers contributors and then that can me put in the ```/contributor``` page 
ofviously I will create it on react.

**Comment by ArunTeltia** [comment]
also that js will be in website s ota that will be fetched so that each mantainer can create a PR and I dont need to add it manually XD

**Comment by LordShenron** [comment]
> I am thinking of creating a seperate page for it, Send me the Card based theme that you want, i will create a js file for all the mantainers contributors and then that can me put in the `/contributor` page
> ofviously I will create it on react.

Only do it in react if you are it will be a single paged application.

**Comment by vedikaag99** [comment]
So should I close this PR for the time being?
@ArunTeltia I can also help in making the react component if you want.

**Comment by ArunTeltia** [comment]
Okay so do you want to make contributors page @vedikaag99 ? will give you an access and also the type of cards you need to make

**Comment by ArunTeltia** [comment]
Screenshot (101)
@LordShenron should we create this type(No images will redirect to github id of contributors and mantainers), This Looks sleek and sexy

**Comment by ArunTeltia** [comment]
https://pixysos.com/team

**Comment by vedikaag99** [comment]
> Okay so do you want to make contributors page @vedikaag99 ? will give you an access and also the type of cards you need to make

Would be happy to help! 😁

**Review by yasharth291 — APPROVED** [review]

**Pull request closed without merging**
