### PR TITLE
Scroll-top arrow added to website

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
Fixed issue #279 

I have added scroll-top arrow to the website.
Please view my PR @ArunTeltia  @LordShenron

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Can you share an image of this one @Bhavya-Sehgal

**Comment by Bhavya-Sehgal** [comment]
scroll

@ArunTeltia

**Comment by ArunTeltia** [comment]
Looks good to me @LordShenron , do you want to give suggestion on how the button should look, for me its looking good

**Comment by LordShenron** [comment]
@ArunTeltia Merge it

**Pull request merged**
