### PR TITLE
Branch2

### PR DESCRIPTION
**Pull request by Shivam-Shandilya1**
Added sponsors.css to contain internal CSS command to an external file and gain ease in modifying it.

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Give me your discord id I will contact you @Shivam-Shandilya1 I will help you with these i guess you are getting lost here

**Comment by Shivam-Shandilya1** [comment]
My discord id is Shivam(P) #4281

**Comment by Shivam-Shandilya1** [comment]
Thanks for coming up to guide me, It will be helpful to me.

**Comment by yasharth291** [comment]
Hey @Shivam-Shandilya1  can you please remove the merge conflicts

**Pull request closed without merging**
