### PR TITLE
New readme

### PR DESCRIPTION
**Pull request by cryptofox17**
Updated the readme.md file and added snapshots to the images folder

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Excellent @cryptofox17, Looking good to me 
@LordShenron Can you review this

**Review by ArunTeltia — APPROVED** [review]

**Review by LordShenron — APPROVED** [review]
nice.. approved from me.

**Review by rhythmjayee — APPROVED** [review]
Looks nice!!

**Comment by ArunTeltia** [comment]
Taging the parent issue #128

**Pull request merged**
