### PR TITLE
Added  the contact section.

### PR DESCRIPTION
**Pull request by FireQueen-3010**
1) I have added the contact section after the downloads section.
2) Added images for discord, LinkedIn, and email.
3) Put deadlinks for each to be edited when needed.
4) Added the link to the contact section on the navbar as well.
5) Updated the image folder for the discord, LinkedIn, and email images.

Issue #123 .

### CODE REVIEW

**Comment by LordShenron** [comment]
Check this up man..

**Comment by FireQueen-3010** [comment]
@ArunTeltia @LordShenron I have a tiny doubt, please do clarify it. Adding the contact section counts as a small feature of the page and according to gssoc'21 guidelines, as far as I am concerned it comes under level 2. Do you think, it would be worth increasing the issue's level? Hope you consider this and I will glad whatsoever would be your decision. Thank you again!

**Review by rhythmjayee — APPROVED** [review]

**Comment by ArunTeltia** [comment]
Dont worry to much @FireQueen-3010 this will be a level 2 PR, I am not on the laptop so I will review it tomorrow, meanwhile @LordShenron can you please review it

**Comment by FireQueen-3010** [comment]
Thank you so much @ArunTeltia

**Comment by ArunTeltia** [comment]
Looking good to me can you also check @LordShenron, and merge it if it looks good to you

**Comment by FireQueen-3010** [comment]
Hi, please may I know when my pr will be merged? So that I can start working on the other issue on the project as well.

**Comment by FireQueen-3010** [comment]
Hey, @ArunTeltia @LordShenron  just wanted to know when can I expect my pr to be merged so that I can start working on the other issue on the same project as well. Thanks again!

**Review by yasharth291 — APPROVED** [review]

**Comment by LordShenron** [comment]
> Hey, @ArunTeltia @LordShenron just wanted to know when can I expect my pr to be merged so that I can start working on the other issue on the same project as well. Thanks again!

Sorry for the delay.. I had a got a mountain of work to wrap up. Looking into your PR now.

**Review by LordShenron — CHANGES_REQUESTED** [review]
We don't have any use of Linkedin and Discord. I request if you could instead add Twitter and Telegram as  all our targeted audience is from Telegram and Twitter. 

Once The needed changes are made I will merge this PR.

**Comment by FireQueen-3010** [comment]
ok

**Comment by FireQueen-3010** [comment]
Do I need to resolve the conflicts as well before making the required changes? Please guide me as I am a beginner. @LordShenron

**Comment by LordShenron** [comment]
> Do I need to resolve the conflicts as well before making the required changes? Please guide me as I am a beginner. @LordShenron

If you are planning to make changes to this pr then you can pull the recent changes made to the repo and then fix the conflicting code. Alternatively you can create a new fork and then add contact info to it again and create a new pull request.

**Comment by FireQueen-3010** [comment]
Ok thank you

**Comment by LordShenron** [comment]
> Ok thank you

Now you can do the requested changes and push it to this same PR

**Comment by FireQueen-3010** [comment]
Wow cool, give a few mins, right on, and thanks again!

**Comment by FireQueen-3010** [comment]
done with the necessary changes, please merge if you are satisfied! @LordShenron

**Comment by FireQueen-3010** [comment]
done with the necessary changes merge @LordShenron and also don't forget to increase the level from 1 to 2  as mentioned by @ArunTeltia. Thank you so much!

**Review by LordShenron — APPROVED** [review]

**Comment by FireQueen-3010** [comment]
I'm really sorry if I have spammed with prs but after resloving conflicts i found tiny bugs which are now fixed and good to go. This is the final pr.

**Comment by FireQueen-3010** [comment]
Thank you so much!

**Comment by ArunTeltia** [comment]
Done Thank You @FireQueen-3010

**Pull request merged**
