### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by yasharth291**
created for testing the app

### CODE REVIEW

**Comment by ArunTeltia** [comment]
LGTM but can you add a command that on every issue the tags are assigned to the issue automatically
The tags are: gssoc21 and triage

**Comment by LordShenron** [comment]
Umm, why do we need this here? the page get's auto deployed and it's not a node project.

**Comment by ArunTeltia** [comment]
Just the addition of Travis.yml unless we can use github workflow which may be better for our case, Travis will only overcomplicate things
We can automate somethings like adding the tags whenever an issue created.

**Comment by LordShenron** [comment]
> Just the addition of Travis.yml unless we can use github workflow which may be better for our case, Travis will only overcomplicate things
> We can automate somethings like adding the tags whenever an issue created.

We simply don't need github workflow for this project.. that can be used on download page that is written in vue and needs to be built and deployed manually everytime.

**Comment by ArunTeltia** [comment]
Check my PR @LordShenron

**Pull request closed without merging**
