### PR TITLE
Scroll Bar Color Updated

### PR DESCRIPTION
**Pull request by vibhanshujainiiitr**
It will change the color of the scroll bar to the dark mode which matches the color theme of the website.

### CODE REVIEW

**Comment by ArunTeltia** [comment]
can you share the image of the scrollbar please @vibhanshujainiiitr

**Comment by vibhanshujainiiitr** [comment]
image

### Here is the screenshot of the same.

**Comment by ArunTeltia** [comment]
looks good to me but why is there a vertical scroll bar @vibhanshujainiiitr or is it something else ?

**Comment by vibhanshujainiiitr** [comment]
It is something else.

There is some other error
"Horizontal Navigation" 
This is again a new different issue on which I am working now.

image

**Comment by vibhanshujainiiitr** [comment]
Backlink removed.
#233

**Review by yasharth291 — APPROVED** [review]

**Review by ArunTeltia — APPROVED** [review]

**Comment by ArunTeltia** [comment]
Can be merged @LordShenron

**Pull request merged**
