### PR TITLE
Applid hover effect in Download and COnatct us section issue #261

### PR DESCRIPTION
**Pull request by RahulBansal0502**
When user hover in above sections:
image
image
Check this @LordShenron @ArunTeltia @yasharth291 
Thanks!!

### CODE REVIEW

**Comment by LordShenron** [comment]
You really need to discuss before you do anything. I am not merging anything that is absolutely not needed.

**Comment by RahulBansal0502** [comment]
I create issue first then I made PR @yasharth291 assign me this issue

**Comment by LordShenron** [comment]
> I create issue first then I made PR @yasharth291 assign me this issue

It was assigned to you without proper discussion by him. Sorry, it was an issue from our side.

**Comment by RahulBansal0502** [comment]
No problem

**Pull request closed without merging**
