### PR TITLE
scroll to the hash links feature added

### PR DESCRIPTION
**Pull request by anujarora0502**
Now navbar links are scrollable it will scroll to the specified section.

### CODE REVIEW

**Comment by LordShenron** [comment]
@anujarora0502

**Comment by LordShenron** [comment]
Test this change Arun and notify me.

**Comment by ArunTeltia** [comment]
we dont want to use jquery 
@anujarora0502 try to do this in pure js

**Comment by anujarora0502** [comment]
ok

**Comment by anujarora0502** [comment]
check now

**Comment by ArunTeltia** [comment]
Looks good to me squash the commits and then send a pr

**Pull request merged**
