### PR TITLE
Revamp Footer issue #236

### PR DESCRIPTION
**Pull request by RahulBansal0502**
I revamped the footer page against issue #236 @ArunTeltia @yasharth291 . Please merge this.

### CODE REVIEW

**Review by yasharth291 — APPROVED** [review]

**Comment by LordShenron** [comment]
> I revamped the footer page against issue #236 @ArunTeltia @yasharth291 . Please merge this.

A preview will make reviewing many times easier

**Comment by RahulBansal0502** [comment]
May I add ss of the changes @LordShenron

**Comment by RahulBansal0502** [comment]
image

**Comment by yasharth291** [comment]
Hey rahul please do mention issue which are u going to fix like Fixes  #236

**Review by yasharth291 — APPROVED** [review]

**Review by yasharth291 — APPROVED** [review]

**Comment by RahulBansal0502** [comment]
I revamp the footer issue #236 and attach screenshot here for your reference so that It will be easy for you to review it.

**Comment by RahulBansal0502** [comment]
@ArunTeltia @LordShenron please look this issue against issue #236

**Comment by ArunTeltia** [comment]
I am not sure why are we focusing on footer so much our priority should be to work on stats page footer if i am correct 
@LordShenron can you please check this PR I am not sure what to make out of this PR

**Comment by LordShenron** [comment]
> I am not sure why are we focusing on footer so much our priority should be to work on stats page footer if i am correct
> @LordShenron can you please check this PR I am not sure what to make out of this PR

There is no point in showing the same options that we have on the navbar in the footer as well.

**Pull request closed without merging**
