### PR TITLE
removed unused css classes

### PR DESCRIPTION
**Pull request by cryptofox17**
Found out the unused class using coverage in chrome dev tools and also ensured that removing the classes had no impact on the UI on all device sizes.

### CODE REVIEW

**Comment by yasharth291** [comment]
is the website running after removing this?

**Comment by cryptofox17** [comment]
@yasharth291 yes, I tested it and it runs fine

**Review by yasharth291 — APPROVED** [review]

**Review by LordShenron — APPROVED** [review]
I tested it out just now, seems to be working fine. Approving it. 
@ArunTeltia follow up with your test.

**Comment by LordShenron** [comment]
Also, I think there are much more unused CSS. If you are going to commit more changes then keep them adding here.

**Comment by ArunTeltia** [comment]
Lets just create new Pr for every CSS file so that it is easy to be reviewed Lets just merge these commits then

**Comment by LordShenron** [comment]
> Lets just create new Pr for every CSS file so that it is easy to be reviewed Lets just merge these commits then

We can just squash all the changes for this in 1 commit, creating new pr for each class will become a pain in the ass

**Comment by Vishal-raj-1** [comment]
@LordShenron If you are project admin or mentor, Please add label to all the PRs otherwise score of the participants will not be updated. Basically You have to add gssoc21 and levels label to PR as well. So that we(developer team of GSSOC) can evaluate score of participants.

@cryptofox17 It may be possible mentor or admin forgot to add label to your's PRs so It's your duty. As soon as PR is merged You must remind mentor/admin to add labels to the PRs. Otherwise PR score will not be added in total score. 

Thanks for contributing in GSSOC'21
Regards 
Vishal
(Developer Team Member of GSSOC'21)

**Comment by LordShenron** [comment]
> @LordShenron If you are project admin or mentor, Please add label to all the PRs otherwise score of the participants will not be updated. Basically You have to add gssoc21 and levels label to PR as well. So that we(developer team of GSSOC) can evaluate score of participants.
> 
> @cryptofox17 It may be possible mentor or admin forgot to add label to your's PRs so It's your duty. As soon as PR is merged You must remind mentor/admin to add labels to the PRs. Otherwise PR score will not be added in total score.
> 
> Thanks for contributing in GSSOC'21
> Regards
> Vishal
> (Developer Team Member of GSSOC'21)

Due to the load of work @ArunTeltia and me sometimes forget adding labels to pull requests. We will add it as soon as possible.

**Comment by Vishal-raj-1** [comment]
@LordShenron I can understand. No Problem !! Best of Luck for your open source journey !!

**Pull request merged**
