### PR TITLE
add contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #131 
Added contributing.md
It is a simple file which even beginners can use to contribute to open source 
Added the following
1.Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream

### CODE REVIEW

**Review by rhythmjayee — COMMENTED** [review]
Looks nice!!

**Review by rhythmjayee — APPROVED** [review]

**Comment by ArunTeltia** [comment]
Looks nice to me as well @LordShenron review this and then merge it

**Review by ArunTeltia — APPROVED** [review]

**Review by LordShenron — APPROVED** [review]

**Review by rhythmjayee — APPROVED** [review]

**Comment by khareyash05** [comment]
Thank You @ArunTeltia @LordShenron @rhythmjayee 
Could you add a GSSOC label to the same please?

**Comment by khareyash05** [comment]
@LordShenron could you please let me know what is the level of the issue?

**Pull request merged**
