### PR TITLE
fixed header and footer issues

### LINKED ISSUE #270: Uniformity with the footer in stats
The footer in our landing and download page are very different. We want to design the footer in our landing page similar to the download page.

### PR DESCRIPTION
**Pull request by cryptofox17**
Closes #270 

### Screenshot
- before  

Screenshot (172)
Screenshot (171)

- after 

Screenshot (170)
Screenshot (169)

### CODE REVIEW

**Review by ArunTeltia — COMMENTED** [review]
Can you share an image for the pc view @cryptofox17  for the footer otherwise it looks good

**Review by ArunTeltia — COMMENTED** [review]
Can you share an image for the pc view @cryptofox17  for the footer otherwise it looks good

**Comment by cryptofox17** [comment]
@ArunTeltia 
Screenshot (174)
Screenshot (173)

**Comment by ArunTeltia** [comment]
Merge @LordShenron

**Pull request merged**
