### PR TITLE
Added navbar button effects on homepage

### PR DESCRIPTION
**Pull request by FireQueen-3010**
-> Followed the UI guidelines provided in the readme file.
-> Added hover and click effects both on active and focus states.
-> Fixed margin between the button while hovering.

This resolves issue #122.

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review and merge. Thanks!

**Comment by FireQueen-3010** [comment]
after the merge, can I raise an issue for changing other buttons on the homepage as well? (With different animations maintaining the same UI)

**Comment by ArunTeltia** [comment]
Can you share the image of the changes please @FireQueen-3010

**Comment by ArunTeltia** [comment]
Can Anyone of you review this PR

**Comment by FireQueen-3010** [comment]
Sorry for the delay, here is a demo video of how the nav buttons are animated. @ArunTeltia @LordShenron @rhythmjayee @yasharth291  [https://drive.google.com/file/d/1AKI1ZMHc_TvLzG45-A5W4qOciuV5rNoS/view?usp=sharing](url)

**Comment by FireQueen-3010** [comment]
Sorry for the delay, here is a demo video of the animated buttons. @ArunTeltia @LordShenron @rhythmjayee @yasharth291 

[https://drive.google.com/file/d/1AKI1ZMHc_TvLzG45-A5W4qOciuV5rNoS/view?usp=sharing](url)

**Comment by ArunTeltia** [comment]
The link is not working @FireQueen-3010 can you have a look at it

**Comment by FireQueen-3010** [comment]
Added the video directly now @ArunTeltia . Sorry for the again!

**Comment by LordShenron** [comment]
As shown by the dcs-soni in this issue, the design of navbar is so much better. I also personally don't like the design of these buttons in navbar. 

Refer to: https://github.com/ProjectSakura/ProjectSakura.github.io/issues/148

**Comment by ArunTeltia** [comment]
Can you create the buttons as shown in the #148 @FireQueen-3010

**Comment by FireQueen-3010** [comment]
Yes, I can, so the current design can I add on the other issue #147 instead 'cause maybe this design (which matches the UI criteria ) will look good on normal buttons on the homepage and update the one you suggested for the navbar? @ArunTeltia @LordShenron

**Comment by ArunTeltia** [comment]
Can you gave your discord id to me i will explain everything to you there

**Comment by FireQueen-3010** [comment]
discord : @Diksha(p)

**Comment by LordShenron** [comment]
> Yes, I can, so the current design can I add on the other issue #147 instead 'cause maybe this design (which matches the UI criteria ) will look good on normal buttons on the homepage and update the one you suggested for the navbar? @ArunTeltia @LordShenron

Currently we have two separate issues, one is for navbar redesigning and the other one that you opened. You can leave the navbar changes on the other guy as he will be doing for all pages and you can focus on redesigning other buttons as per the design guidelines..

hopefully i was clear enough.

**Comment by FireQueen-3010** [comment]
Ok, Thank you @LordShenron

**Pull request closed without merging**
