### PR TITLE
Refactored the modal page on web and mobile version

### PR DESCRIPTION
**Pull request by FireQueen-3010**
Closes ##158

refactor

### Screenshot

Before refactoring (web version)
modalPageBeforePic

Before refactoring (mobile version)
modalmobileBefore

After refactoring (web version)

modalafterpic

After refactoring (mobile version)
modalMobileVersion

Final result :

https://user-images.githubusercontent.com/59244300/111519088-c07c5400-877c-11eb-858c-8bfd9e16044a.mp4

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review my pr @LordShenron @ArunTeltia @rhythmjayee

**Comment by LordShenron** [comment]
Have you tried it in phone view?

**Comment by FireQueen-3010** [comment]
Yeah I fixed the css in the mobile version too and yeah I did view it in the phone view .

**Comment by FireQueen-3010** [comment]
Please review it and if you want me to make further changes, let me know! :)

**Review by LordShenron — CHANGES_REQUESTED** [review]
The centered texts on the modals are not looking good

**Comment by FireQueen-3010** [comment]
Okay

**Comment by FireQueen-3010** [comment]
Should I change color and make it little cleaner or completely change html as well?

**Comment by LordShenron** [comment]
> Should I change color and make it little cleaner or completely change html as well? @LordShenron

If you think you can redesign it.. then please do.

**Comment by FireQueen-3010** [comment]
Okay

**Comment by FireQueen-3010** [comment]
Please review : 

image

**Comment by FireQueen-3010** [comment]
I tried changing the text completely but I am unable to find where it is written. It was absent in html and js files.

**Comment by LordShenron** [comment]
> Please review : @LordShenron @ArunTeltia . I fixed the media queries for all devices as well.
> 
> image

oouch!!! That cyan color in modal gave me a heart attack xD.. 
@ArunTeltia can you please help her with the color scheme?

**Comment by FireQueen-3010** [comment]
Should I go for the clrs used in the nav bar button hover? @LordShenron

**Comment by ArunTeltia** [comment]
I am not sure myself the color should be shame or maybe we should use some custom image as background to make it look better 
The close button color will be better if it's blue
Green on this theme is looking kinda dull to me not gonna lie

**Comment by FireQueen-3010** [comment]
Ok I'll try blue theme then @ArunTeltia

**Comment by ArunTeltia** [comment]
Also check for the text, I am sure the "XIAOMI REDMI NOTE 8/8T | GINKGO (SUPPORT DROPPED)" will overflow in heading

**Comment by FireQueen-3010** [comment]
Oh ok, thanks for the clue!

**Comment by FireQueen-3010** [comment]
image
@LordShenron , is this fine? Also the headings are not overflowing and I added scrollers as well on media queries. If It is fine ill make a pr else you may suggest further changes.

**Comment by LordShenron** [comment]
> image
> @LordShenron , is this fine? Also the headings are not overflowing and I added scrollers as well on media queries. If It is fine ill make a pr else you may suggest further changes.

It looks really good but I still don't like the centered text.. can you move it to left. Then I will approve this PR to be merged.

**Comment by FireQueen-3010** [comment]
Okay

**Comment by FireQueen-3010** [comment]
image
Now?

**Comment by FireQueen-3010** [comment]
Made the pr @LordShenron, do review :)

**Pull request merged**
