### PR TITLE
Validated blog.html

### PR DESCRIPTION
**Pull request by FireQueen-3010**
Part of #208

1) Added doctype, lang to html
2) Refactored deprecated usages
3) Removed duplicated body tags
4) Refactored isolated tags
5) Refactored stray tags
6) Removed unnecessary attributes
7) Removed center tags and refactored them using css
8) Added double instead of single quotes wherever required.

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ArunTeltia @LordShenron

**Comment by ArunTeltia** [comment]
Can I get the image of the blog page in both mobile view and desktop view 
anyways it looks good to me nonetheless

**Comment by FireQueen-3010** [comment]
image
image

**Comment by ArunTeltia** [comment]
LGTM Thank You

**Pull request merged**
