### PR TITLE
Refactored buttons according UI on Downloads page and fixed some button issues.

### PR DESCRIPTION
**Pull request by FireQueen-3010**
Issue : #155

image
image

Made hover property according secondary buttons provided in the UI. 

https://user-images.githubusercontent.com/59244300/111299135-955b0d00-8675-11eb-851a-904a5303a653.mp4

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please accept my pr @ArunTeltia @LordShenron .

**Review by LordShenron — APPROVED** [review]
Looks good to me

**Comment by FireQueen-3010** [comment]
gssoc tag and level(according to issue) tag ? 😅

**Comment by LordShenron** [comment]
> gssoc tag and level(according to issue) tag ? sweat_smile @LordShenron . Thanks again!

Issue https://github.com/ProjectSakura/ProjectSakura.github.io/issues/155 is already tagged and this pull request references it so there is no need to tag it again

**Comment by FireQueen-3010** [comment]
Oh I thought even merge needs tag 'cause my score didn't get updated and it doesn't ususally if there are no tags in the merge as well. Thanks! :)

**Comment by FireQueen-3010** [comment]
Thank you!

**Pull request merged**
