### PR TITLE
Added  back to top button in index.html

### LINKED ISSUE #199: Move to top button
I am always frustrated when I have to scroll the page back to top every time.
There should be a back to top button with smooth scrolling.

### Proposal & Constraints

I can try to add this feature.

### PR DESCRIPTION
**Pull request by arpit456jain**
Closes #199 

[feature] back to top button added.

### Screenshot

https://user-images.githubusercontent.com/55352601/112809374-92114980-9097-11eb-8658-4cf0afecb674.mp4

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Looking Great thank you for contributing to Project Sakura @arpit456jain , Merge it @LordShenron

**Comment by arpit456jain** [comment]
> Looking Great thank you for contributing to Project Sakura @arpit456jain , Merge it @LordShenron

@ArunTeltia the issue #199 was still not assigned to me kindly assign it to me otherwise may be I will not any points for it

**Comment by arpit456jain** [comment]
@LordShenron please review my PR

**Comment by ArunTeltia** [comment]
He will review it @arpit456jain  right now he is on a break , don't worry about it 🎉

**Pull request merged**
