### PR TITLE
Removed few unnecessary classes

### LINKED ISSUE #116: Remove dead code
There are many css classes that are not being used in the project you can find that out and can delete it from the project. 

The level of this issue will depend upon the number of lines removed from the css files 

Steps
1. Delete the css that is not being used in the project
2. Check if the project has still the same UI

### PR DESCRIPTION
**Pull request by cryptofox17**
Partly Closes #116 
Since there are many unused classes for ease of review I have decided on work on this in parts.

In this PR I have removed : 
```
.hide-text

.btn-primary, btn-success, btn-danger, btn-warning, btn-info and the related focus effects etc for the same

.text-success, .text- info, text-warning, .muted, a links with .success, .info, error etc
.input-mini, .input-small, .input-medium, .input-large, .input-xlarge, .input-xxlarge 

.icon- classes

.invisible , .hide-text , .well classes .help-  and related
.badge, .label and related 

.navbar-link 
.img-rounded, .img-polaroid
```

### CODE REVIEW

**Comment by ArunTeltia** [comment]
have you tested all the pages @cryptofox17 ?
If these are the file changes than I can tell this is an insane PR

**Comment by cryptofox17** [comment]
@AdityaTeltia  yeah I tested them. 

removed_css_sakura

**Comment by ArunTeltia** [comment]
@LordShenron Merge it Lets see, size of the project ⬇⬇⬇(almost by 0.4mb)

**Comment by ArunTeltia** [comment]
I checked I dont find any errors ,TYSM @cryptofox17

**Pull request merged**
