### PR TITLE
Solved hover issue

### PR DESCRIPTION
**Pull request by tanishq-arya**
1. Modified html for screenshot links added target="_blank"
2. Changed style for span-tiles in features section

### CODE REVIEW

**Comment by yasharth291** [comment]
Yeah its write for merging @LordShenron  can you please look and see whether it is right to merge or not

**Comment by LordShenron** [comment]
Works fine.. the shadow look a bit odd while hovering. Think you can tone it down a little bit?

**Comment by tanishq-arya** [comment]
> Works fine.. the shadow look a bit odd while hovering. Think you can tone it down a little bit?

Yes I can. So should I keep it only from single side or keep it equal but less from all sides ?

**Comment by LordShenron** [comment]
> > Works fine.. the shadow look a bit odd while hovering. Think you can tone it down a little bit?
> 
> Yes I can. So should I keep it only from single side or keep it equal but less from all sides ?

I don't think shadow is needed at all because the card lights up and that much is enough.

**Review by LordShenron — APPROVED** [review]
Looks fine now.. approving

**Comment by ArunTeltia** [comment]
Looks Fine to me as well @LordShenron  merge it when you get time also add the tags to it

**Review by ArunTeltia — APPROVED** [review]

**Comment by tanishq-arya** [comment]
@LordShenron can you please add level label to this PR. My score is showing NULL.

**Comment by ArunTeltia** [comment]
I am so sorry for the late addition @tanishq-arya here you go

**Comment by tanishq-arya** [comment]
> I am so sorry for the late addition @tanishq-arya here you go
:) No issues I was just checking if my score pops up, it is still null.

**Pull request merged**
