### PR TITLE
validated download.html

### LINKED ISSUE #208: Validate HTML
### Evidence / Screenshot (if possible)
image

### Steps to Reproduce

1. check here https://validator.w3.org/nu/?doc=https%3A%2F%2Fprojectsakura.xyz%2F

* Actual: 
* Expected: 

### Details

- **Browser type/version?** 
- **Operating system?**

### PR DESCRIPTION
**Pull request by tanishq-arya**
Closes #208 

1. Removed duplicate class attribute.
2. Added offset=0 (default) for stop elements
3. Added alt attributes to images.

### Screenshot

image
image

### CODE REVIEW

**Comment by tanishq-arya** [comment]
I have added alt like project sakura logo and sponsor logo where required. If you want any changes let me know.

**Comment by ArunTeltia** [comment]
looks really good @tanishq-arya, the only thing i wanna know is whether alt is important in images or not ? Just for the learning fact tho

@LordShenron merge kar bruh

**Comment by tanishq-arya** [comment]
> looks really good @tanishq-arya, the only thing i wanna know is whether alt is important in images or not ? Just for the learning fact tho
> 
> @LordShenron merge kar bruh

It is for the backup and semantic purposes as well. For example if the image is not loaded then the alt tag will be displayed. And semantically for specially changed people like if someone is blind and enables the auto reader for the website then the reader will say the alt tag {project sakura logo} like this.

Here I changed the href tag so the image is not displayed
image

**Comment by tanishq-arya** [comment]
We can add 
img {
  color:#FFF;
}
in the style so that the user can see just in case the image doesn't load.

**Comment by ArunTeltia** [comment]
OHOOOOOOO Never thought of user that are not able to see the picture because of low speed net definately something to look

For the audience with low internet speed, do we need to do it @tanishq-arya (asking for advice)

**Comment by tanishq-arya** [comment]
> OHOOOOOOO Never thought of user that are not able to see the picture because of low speed net definately something to look
> 
> For the audience with low internet speed, do we need to do it @tanishq-arya (asking for advice)

I would have to check for the speed thing but alt is displayed when the image can't be fetched I guess. i'll update you on this.

**Comment by tanishq-arya** [comment]
I checked on w3 schools and it says alt attribute is useful in case of slow internet connection too. 

We have already solved the validator issues so I guess alt is defined already for the current set of images. In future if we add more images we have to add the alt attribute too.

**Pull request merged**
